# Generated by Django 5.2.6 on 2025-09-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок продукта')),
                ('image', models.ImageField(upload_to='product/', verbose_name='фото продукта')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=250, verbose_name='ключевые слова (keywords)')),
                ('description', models.CharField(max_length=200, verbose_name='описание (description)')),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'seo-оптимизатор',
                'verbose_name_plural': 'seo-оптимизатор (Product)',
            },
        ),
        migrations.CreateModel(
            name='TextList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок списка')),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'список текста',
                'verbose_name_plural': 'списки текста',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='пункт списка')),
                ('fk_textlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.textlist')),
            ],
            options={
                'verbose_name': 'пункт списка',
                'verbose_name_plural': 'пункты списка',
            },
        ),
    ]
