# Generated by Django 5.2.6 on 2025-09-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt',
            field=models.CharField(max_length=200, null=True, verbose_name='alt-текст фото'),
        ),
    ]
