# Generated by Django 5.2.6 on 2025-09-26 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='fk_textlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='product.textlist'),
        ),
        migrations.AlterField(
            model_name='point',
            name='text',
            field=models.CharField(help_text='текст пункта до 250 знаков', max_length=250, verbose_name='пункт списка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alt',
            field=models.CharField(help_text='alt-текст к фото продукта', max_length=200, null=True, verbose_name='alt-текст фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='фото продукта в формате .jpg или .png', upload_to='product/', verbose_name='фото продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='заголовок продукта до 200 знаков', max_length=200, verbose_name='заголовок продукта'),
        ),
        migrations.AlterField(
            model_name='productseo',
            name='description',
            field=models.CharField(help_text='SEO описание до 200 знаков', max_length=200, verbose_name='описание (description)'),
        ),
        migrations.AlterField(
            model_name='productseo',
            name='keywords',
            field=models.CharField(help_text='SEO ключевые слова через запятую, до 250 знаков', max_length=250, verbose_name='ключевые слова (keywords)'),
        ),
        migrations.AlterField(
            model_name='textlist',
            name='title',
            field=models.CharField(help_text='заголовок списка до 250 знаков', max_length=250, verbose_name='заголовок списка'),
        ),
    ]
