# Generated by Django 5.2.6 on 2025-09-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_point_fk_textlist_alter_point_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productseo',
            options={'verbose_name': 'seo-оптимизатор', 'verbose_name_plural': 'seo-оптимизатор (Product Page)'},
        ),
    ]
