# Generated by Django 5.2.6 on 2025-09-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст на главной')),
            ],
            options={
                'verbose_name': 'контент на главную страницу',
                'verbose_name_plural': 'главная',
            },
        ),
        migrations.CreateModel(
            name='IndexSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=250, verbose_name='ключевые слова (keywords)')),
                ('description', models.CharField(max_length=200, verbose_name='описание (description)')),
                ('fk_index', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.index')),
            ],
            options={
                'verbose_name': 'seo-оптимизатор',
                'verbose_name_plural': 'seo-оптимизатор (Index)',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='физический адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='долгота')),
                ('fk_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.index')),
            ],
            options={
                'verbose_name': 'местоположение',
                'verbose_name_plural': 'местоположение',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя изображения')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='изображение')),
                ('alt', models.CharField(max_length=200, verbose_name='alt-текст')),
                ('fk_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.index')),
            ],
            options={
                'verbose_name': 'слайдер',
                'verbose_name_plural': 'слайдер',
            },
        ),
    ]
