# Generated by Django 5.2.6 on 2025-09-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_location_address_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя отправителя')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail отправителя')),
                ('message', models.TextField(verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'обратная связь',
                'verbose_name_plural': 'обратная связь',
            },
        ),
        migrations.AlterModelOptions(
            name='indexseo',
            options={'verbose_name': 'seo-оптимизатор', 'verbose_name_plural': 'seo-оптимизатор (Index Page)'},
        ),
        migrations.AlterField(
            model_name='index',
            name='text',
            field=models.TextField(help_text='введите текст статьи на главной странице', verbose_name='текст на главной'),
        ),
        migrations.AlterField(
            model_name='index',
            name='title',
            field=models.CharField(help_text='введите заголовок главной страницы', max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='indexseo',
            name='description',
            field=models.CharField(help_text='SEO описание до 200 знаков', max_length=200, verbose_name='описание (description)'),
        ),
        migrations.AlterField(
            model_name='indexseo',
            name='keywords',
            field=models.CharField(help_text='SEO ключевые слова через запятую, до 250 знаков', max_length=250, verbose_name='ключевые слова (keywords)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, help_text='введите широту в формате 00.00', null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, help_text='введите долготу в формате 00.00', null=True, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='alt',
            field=models.CharField(help_text='alt-текст к слайду', max_length=200, verbose_name='alt-текст'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(help_text='слайд в формате .jpg или .png', upload_to='slider/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(help_text='имя слайда до 200 знаков', max_length=200, verbose_name='имя изображения'),
        ),
    ]
