# Generated by Django 5.2.6 on 2025-09-27 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_feedback_alter_indexseo_options_alter_index_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время отправки'),
        ),
    ]
